apiVersion: v1
kind: Pod
metadata:
  name: echo-pods-pod
  labels:
    app: echo-pods
spec:
  containers:
    - name: echo-pods
      image: muruu1/echo-pods:v1.0
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 80
